//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.billproducts = new HashSet<billproduct>();
            this.infobills = new HashSet<infobill>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> buy_date { get; set; }
        public Nullable<int> discount_percent { get; set; }
        public Nullable<bool> transport_status { get; set; }
        public Nullable<int> price_total { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<bool> buy_status { get; set; }
        public Nullable<int> buyer_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billproduct> billproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infobill> infobills { get; set; }
        public virtual user user { get; set; }
    }
}
