//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int Id { get; set; }
        public string comment1 { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> commenter_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
