//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infobill
    {
        public int Id { get; set; }
        public string address { get; set; }
        public string method { get; set; }
        public string note { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> bill_id { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
