//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBanHang6Entities : DbContext
    {
        public QuanLyBanHang6Entities()
            : base("name=QuanLyBanHang6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<billproduct> billproducts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<infobill> infobills { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
